"""done

Revision ID: 17254547afde
Revises: 7116d08f968c
Create Date: 2024-10-19 11:11:33.893859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17254547afde'
down_revision = '7116d08f968c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klasifikasi_buku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deweyNoClass', sa.String(length=250), nullable=False),
    sa.Column('narasi_klasifikasi', sa.String(length=250), nullable=True),
    sa.Column('subject', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('klasifikasi_buku')
    # ### end Alembic commands ###
