"""done

Revision ID: 5b07c0280544
Revises: 381ba80fdf1b
Create Date: 2024-08-28 09:16:56.075316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b07c0280544'
down_revision = '381ba80fdf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fotoprofile', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('path', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('path')
        batch_op.drop_column('fotoprofile')

    # ### end Alembic commands ###
