"""updateMaster

Revision ID: 7116d08f968c
Revises: 1a86093ff9d9
Create Date: 2024-10-01 09:52:23.572796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7116d08f968c'
down_revision = '1a86093ff9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_buku', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kota', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('tahun_terbit', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('editor', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('ilustrator', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_buku', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ilustrator')
        batch_op.drop_column('editor')
        batch_op.drop_column('tahun_terbit')
        batch_op.drop_column('kota')

    # ### end Alembic commands ###
