"""update_sinopsis

Revision ID: 7ecc10db8055
Revises: 17254547afde
Create Date: 2024-10-24 10:00:27.095476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecc10db8055'
down_revision = '17254547afde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sinopsis_buku', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_class', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sinopsis_buku', schema=None) as batch_op:
        batch_op.drop_column('no_class')

    # ### end Alembic commands ###
