name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login Docker
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Pull Docker image
      run: sudo docker pull farih652/digitallibrary-backend:latest
    - name: Delete Old docker container
      run: sudo docker rm -f digitallibrary-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name digitallibrary-container farih652/digitallibrary-backend
