name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  Deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p dckr_pat_NEpMbTUOvtO7-b9ZP0pHMyI4S0s
    - name: Pull Docker image
      run: sudo docker pull farih652/digitallibrary-backend:latest
    - name: Delete Old docker container
      run: sudo docker rm -f digitallibrary-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name digitallibrary-container farih652/digitallibrary-backend
