name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t farih652/digitallibrary-backend .
    - name: Push to Dockerhub
      run: docker push farih652/digitallibrary-backend:latest


  Deploy:
    needs: [build]
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull farih652/digitallibrary-backend:latest
    - name: Delete Old docker container
      run: sudo docker rm -f digitallibrary-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8770:8770 --name digitallibrary-container farih652/digitallibrary-backend
